let currentGalleryState=null;
function findSecurityPanel(){const buttons=[...document.querySelectorAll('button')];const a=buttons.find(b=>(b.textContent||'').includes('Verrouiller les invités'));const b=buttons.find(b=>(b.textContent||'').includes('Verrouiller toute la galerie'));if(a&&b){let n=a.parentElement;for(let i=0;i<8&&n;i++,n=n.parentElement)if(n.contains(b))return n;}return null;}
function currentOrganizerToken(){const input=[...document.querySelectorAll('input')].find(el=>String(el.value||'').includes('/api/lumabooth/event/'));const m=String(input?.value||'').match(/\/api\/lumabooth\/event\/([^/?#]+)/i);return m?decodeURIComponent(m[1]):'';}
function makeButton(label,enabled,onClick){const b=document.createElement('button');b.type='button';b.textContent=`${enabled?'🟢':'🔴'} ${label} : ${enabled?'Autorisé':'Interdit'}`;b.style.marginRight='8px';b.style.marginTop='8px';b.addEventListener('click',onClick);return b;}
async function api(url,options){const r=await fetch(url,options);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||'Opération impossible.');return d;}
async function resolveCurrentGallery(){const token=currentOrganizerToken();if(!token)throw new Error('Jeton organisateur introuvable.');const list=await api('/api/admin/galleries');const gallery=(list.galleries||[]).find(g=>String(g.organizerToken||'')===token);if(!gallery)throw new Error('Galerie liée à ce portail introuvable.');const detail=await api(`/api/admin/galleries/${encodeURIComponent(gallery.id)}`);const event=detail.event||{};return{eventId:event.id||gallery.id,download:event.guestDownloadEnabled!==false,delete:event.guestDeleteEnabled===true};}
async function savePermission(state,changes){const body={};if(Object.prototype.hasOwnProperty.call(changes,'guestDownloadEnabled'))body.guestDownloadEnabled=changes.guestDownloadEnabled;if(Object.prototype.hasOwnProperty.call(changes,'guestDeleteEnabled'))body.guestDeleteEnabled=changes.guestDeleteEnabled;const data=await api(`/api/admin/galleries/${encodeURIComponent(state.eventId)}/guest-rights`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});state.download=data.guestDownloadEnabled!==false;state.delete=data.guestDeleteEnabled===true;}
function mountControls(){const panel=findSecurityPanel();if(!panel||!currentGalleryState)return;document.getElementById('lp28-guest-rights')?.remove();const state=currentGalleryState;const box=document.createElement('div');box.id='lp28-guest-rights';box.style.cssText='margin-top:14px;padding-top:12px;border-top:1px solid rgba(128,128,128,.25);width:100%';box.innerHTML='<strong>🔐 Droits des invités</strong><div class="muted" style="margin-top:4px">Choisis ce que les invités peuvent faire dans la galerie de cet événement.</div><div id="lp28-guest-rights-buttons"></div>';panel.appendChild(box);const buttons=box.querySelector('#lp28-guest-rights-buttons');const render=()=>{buttons.innerHTML='';const download=makeButton('Téléchargement',state.download,async()=>{download.disabled=true;try{await savePermission(state,{guestDownloadEnabled:!state.download});render();}catch(e){alert(e.message);download.disabled=false;}});const del=makeButton('Suppression',state.delete,async()=>{const next=!state.delete;if(next&&!confirm('Autoriser les invités à supprimer définitivement des photos de cet événement ?'))return;del.disabled=true;try{await savePermission(state,{guestDeleteEnabled:next});render();}catch(e){alert(e.message);del.disabled=false;}});buttons.append(download,del);};render();}
async function ensureMounted(){if(document.getElementById('lp28-guest-rights'))return;const panel=findSecurityPanel();if(!panel)return;const loading=document.createElement('div');loading.id='lp28-guest-rights';loading.style.cssText='margin-top:14px;padding-top:12px;border-top:1px solid rgba(128,128,128,.25);width:100%';loading.innerHTML='<strong>🔐 Droits des invités</strong><div class="muted" style="margin-top:4px">Chargement…</div>';panel.appendChild(loading);try{currentGalleryState=await resolveCurrentGallery();mountControls();}catch(e){loading.innerHTML=`<strong>🔐 Droits des invités</strong><div class="muted" style="margin-top:4px">⚠️ ${e.message}</div>`;}}
export function installGuestPermissionAdmin(){let scheduled=false;const run=()=>{if(scheduled)return;scheduled=true;setTimeout(()=>{scheduled=false;ensureMounted();},80);};new MutationObserver(run).observe(document.documentElement,{childList:true,subtree:true});window.addEventListener('load',run);document.addEventListener('click',()=>setTimeout(run,120));setTimeout(run,0);}
