import { buildBrowserZip } from "./clientZip";
function mediaIdFromCard(card){const media=card?.querySelector("img[src*='/memories/'],video[src*='/memories/']");const src=media?.getAttribute("src")||"";const match=src.match(/\/memories\/([^/?#]+)\/(?:file|thumbnail)/);return match?decodeURIComponent(match[1]):null;}
function selectedIds(){return [...new Set([...document.querySelectorAll(".memory-card.selected")].map(mediaIdFromCard).filter(Boolean))];}
function portalToken(){const portal=location.pathname.match(/^\/portal\/([^/]+)$/);return portal?portal[1]:null;}
function retryImage(img){if(!img||img.tagName!=="IMG")return;const src=img.getAttribute("src")||"";if(!src.includes("/memories/"))return;const attempts=Number(img.dataset.lp28Retry||0);if(attempts>=3)return;img.dataset.lp28Retry=String(attempts+1);setTimeout(()=>{if(!img.isConnected)return;const current=img.getAttribute("src")||src;const u=new URL(current,location.href);u.searchParams.set("lp28retry",`${Date.now()}-${attempts+1}`);img.src=u.pathname+u.search+u.hash;},350+(attempts*650));}
function prepareGalleryImages(root=document){root.querySelectorAll?.("img[src*='/memories/']").forEach(img=>{if(img.dataset.lp28RetryReady)return;img.dataset.lp28RetryReady="1";img.addEventListener("error",()=>retryImage(img));if(img.complete&&img.naturalWidth===0)retryImage(img);});}
function saveBlob(blob,filename){const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=filename||"LP28-photos.zip";document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
async function fetchJson(url,options){const r=await fetch(url,options);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||"Opération impossible.");return d;}
const guest={checked:false,isGuest:false,download:false,delete:false,selectMode:false,selected:new Set()};
async function detectGuest(){const token=portalToken();if(!token||guest.checked)return;guest.checked=true;try{const d=await fetchJson(`/api/r2/guest-permissions/${encodeURIComponent(token)}`);guest.isGuest=true;guest.download=d.download===true;guest.delete=d.delete===true;renderGuestControls();}catch{guest.isGuest=false;}}
function guestCards(){return [...document.querySelectorAll(".memory-card")].filter(c=>mediaIdFromCard(c));}
function updateGuestCards(){if(!guest.isGuest)return;for(const card of guestCards()){const id=mediaIdFromCard(card);card.classList.toggle("selected",guest.selected.has(id));let check=card.querySelector(".lp28-guest-check");if(guest.selectMode){if(!check){check=document.createElement("button");check.type="button";check.className="memory-select-check lp28-guest-check";check.addEventListener("click",e=>{e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();if(guest.selected.has(id))guest.selected.delete(id);else guest.selected.add(id);updateGuestCards();renderGuestBar();},true);card.prepend(check);}check.textContent=guest.selected.has(id)?"✓":"";}else check?.remove();}}
function renderGuestBar(){if(!guest.isGuest)return;document.getElementById("lp28-guest-selection-bar")?.remove();if(!guest.selectMode)return;const cards=guestCards(),ids=cards.map(mediaIdFromCard).filter(Boolean);const host=document.querySelector("#photos-partagees .memories-heading")||document.querySelector(".memories-heading");if(!host)return;const bar=document.createElement("div");bar.id="lp28-guest-selection-bar";bar.className="memory-selection-bar";bar.style.marginTop="10px";const strong=document.createElement("strong");strong.textContent=`${guest.selected.size} sélectionnée${guest.selected.size>1?'s':''} sur ${ids.length}`;const actions=document.createElement("div");actions.style.cssText="display:flex;gap:8px;flex-wrap:wrap;justify-content:flex-end";const all=document.createElement("button");all.type="button";all.textContent="☑ Tout sélectionner";all.disabled=!ids.length||guest.selected.size===ids.length;all.onclick=()=>{ids.forEach(id=>guest.selected.add(id));updateGuestCards();renderGuestBar();};const none=document.createElement("button");none.type="button";none.textContent="⬜ Tout désélectionner";none.disabled=!guest.selected.size;none.onclick=()=>{guest.selected.clear();updateGuestCards();renderGuestBar();};actions.append(all,none);if(guest.download){const dl=document.createElement("button");dl.type="button";dl.textContent="⬇️ Télécharger la sélection";dl.disabled=!guest.selected.size;dl.onclick=()=>downloadGuest(dl);actions.appendChild(dl);}if(guest.delete){const del=document.createElement("button");del.type="button";del.className="danger";del.textContent="🗑️ Supprimer la sélection";del.disabled=!guest.selected.size;del.onclick=()=>deleteGuest(del);actions.appendChild(del);}bar.append(strong,actions);host.insertAdjacentElement("afterend",bar);}
function renderGuestControls(){if(!guest.isGuest)return;const host=document.querySelector("#photos-partagees .memories-heading");if(!host)return;let toggle=document.getElementById("lp28-guest-select-toggle");if(!(guest.download||guest.delete)){toggle?.remove();return;}if(!toggle){toggle=document.createElement("button");toggle.id="lp28-guest-select-toggle";toggle.className="memory-select-toggle";host.appendChild(toggle);toggle.addEventListener("click",()=>{guest.selectMode=!guest.selectMode;guest.selected.clear();toggle.textContent=guest.selectMode?"Annuler":"☑ Sélectionner";updateGuestCards();renderGuestBar();});}toggle.textContent=guest.selectMode?"Annuler":"☑ Sélectionner";updateGuestCards();renderGuestBar();}
async function downloadGuest(button){const token=portalToken(),ids=[...guest.selected];if(!token||!ids.length)return;const old=button.textContent;button.disabled=true;button.textContent=`📦 Préparation (${ids.length})…`;try{const data=await fetchJson(`/api/r2/guest-zip-links/${encodeURIComponent(token)}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({ids})});const blob=await buildBrowserZip(data.files,(done,total)=>{button.textContent=`☁️ Téléchargement ${done}/${total}…`;});button.textContent="📦 Création du ZIP…";saveBlob(blob,data.filename);}catch(err){alert(err.message||"Téléchargement impossible.");}finally{button.disabled=false;button.textContent=old;}}
async function deleteGuest(button){const token=portalToken(),ids=[...guest.selected];if(!token||!ids.length)return;if(!confirm(`Supprimer définitivement ${ids.length} photo${ids.length>1?'s':''} ?\n\nCette action est irréversible.`))return;const old=button.textContent;button.disabled=true;button.textContent=`🗑️ Suppression (${ids.length})…`;try{await fetchJson(`/api/r2/guest-delete/${encodeURIComponent(token)}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({ids})});location.reload();}catch(err){alert(err.message||"Suppression impossible.");button.disabled=false;button.textContent=old;}}
function ensureOrganizerDeleteButton(){if(guest.isGuest)return;const token=portalToken();if(!token)return;const download=[...document.querySelectorAll("button")].find(b=>b.textContent.includes("Télécharger la sélection"));if(!download||document.getElementById("lp28-delete-selected"))return;const button=document.createElement("button");button.id="lp28-delete-selected";button.type="button";button.className=download.className;button.textContent="🗑️ Supprimer la sélection";button.style.marginLeft="8px";download.insertAdjacentElement("afterend",button);}
export function installZipDownloads(){const refresh=()=>{prepareGalleryImages();detectGuest().then(()=>{if(guest.isGuest)renderGuestControls();else ensureOrganizerDeleteButton();});};const observer=new MutationObserver(mutations=>{for(const mutation of mutations){for(const node of mutation.addedNodes){if(node.nodeType===1){prepareGalleryImages(node);}}}refresh();});observer.observe(document.documentElement,{childList:true,subtree:true});window.addEventListener("load",refresh);prepareGalleryImages();refresh();document.addEventListener("error",event=>{if(event.target?.tagName==="IMG")retryImage(event.target);},true);
 document.addEventListener("click",async event=>{const button=event.target.closest("button");if(!button||guest.isGuest)return;const token=portalToken();if(!token)return;if(button.id==="lp28-delete-selected"){event.preventDefault();event.stopPropagation();event.stopImmediatePropagation();const ids=selectedIds();if(!ids.length){alert("Sélectionne au moins une photo.");return;}if(!confirm(`Supprimer définitivement ${ids.length} photo${ids.length>1?"s":""} ?\n\nCette action est irréversible.`))return;const oldText=button.textContent;button.disabled=true;button.textContent=`🗑️ Suppression (${ids.length})…`;try{await fetchJson(`/api/r2/portal-delete/${encodeURIComponent(token)}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({ids})});location.reload();}catch(err){alert(err.message||"Suppression impossible.");button.disabled=false;button.textContent=oldText;}return;}if(!button.textContent.includes("Télécharger la sélection"))return;const ids=selectedIds();if(!ids.length)return;event.preventDefault();event.stopPropagation();event.stopImmediatePropagation();const oldText=button.textContent;button.disabled=true;button.textContent=`📦 Préparation (${ids.length})…`;try{const data=await fetchJson(`/api/r2/portal-zip-links/${encodeURIComponent(token)}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({ids})});const blob=await buildBrowserZip(data.files,(done,total)=>{button.textContent=`☁️ Téléchargement ${done}/${total}…`;});button.textContent="📦 Création du ZIP…";saveBlob(blob,data.filename);}catch(err){console.error("LP28 ZIP navigateur",err);alert(err.message||"Téléchargement ZIP impossible.");}finally{button.disabled=false;button.textContent=oldText;}},true);
}
